### ISSUE TITLE
Import file scoped to current request instead of file

### ISSUE THREAD

**Issue by gerukin** [AnWeber/httpyac#64] opened 2021-09-11 02:32 UTC
Andreas, thanks for the latest bug fixes / improvements... and for the really nice updated documentation! 🙇‍♂️👍

That being said.. I ran into an issue when doing this:
```
# @import ./external.http

### Some request
# @ref requestName
# ...
```

It doesn't know about `requestName` here.

It works fine when I switch to:
```http
### Some request
# @import ./external.http
# @ref requestName
# ...
```

The manual [says](https://httpyac.github.io/guide/metaData.html#import):
> To reference Requests from other files, these must first be imported. Imported files are enabled for all requests in one file.

But the example uses only one request with no `###` delimiter. It looks like imports are scoped to only one request when `###` delimiters are used.

**Comment by AnWeber** [comment] 2021-09-12 18:06
Thanks for the issue. The cause was that I [cloned the processorContext](https://github.com/AnWeber/httpyac/blob/main/src/utils/httpRegionUtils.ts#L86) but overlooked copying the imports. I have now fixed it by adding an explicit property for extensions

**Closed by AnWeber** 2021-09-12 18:06 UTC
