### ISSUE TITLE
The CLI in version 4.7.1 is broken

### ISSUE THREAD

**Issue by dremekie** [AnWeber/httpyac#123] opened 2021-11-21 01:58 UTC
Running httpyac CLI (e.g. `httpyac --help`) always results in:

```
SyntaxError: Unexpected token '?'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/dwayne/.nvm/versions/node/v12.22.6/lib/node_modules/httpyac/bin/httpyac.js:3:17)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
```

This issue is not seen in version 4.7.0.

**Comment by AnWeber** [comment] 2021-11-21 19:55
I have tested it on both Linux and Win10. In both versions I can run both a `httpyac --help` and `httpyac test.http`. I currently have httpyac support set to [>Node 14.16](https://github.com/AnWeber/httpyac/blob/fe51269b629195b23272d9f3706ea765d2a0c777/package.json#L32). I believe it was because of got only supports same version (https://github.com/sindresorhus/got/blob/main/package.json#L11).
Your path currently contains a reference to version 12.12. Was this version used here?

```
    at Object.<anonymous> (/home/dwayne/.nvm/versions/node/  v12.22.6  /lib/node_modules/httpyac/bin/httpyac.js:3:17)
```

**Comment by AnWeber** [comment] 2021-11-21 20:11
With Node v12 I was able to reproduce the error. I am not sure if I can support the version because too many dependencies require >14. v12 already has End of Life in [April 2022](https://nodejs.org/en/about/releases/) anyway.

**Comment by AnWeber** [comment] 2021-12-05 20:26
The cause was the use of `??`, which is not yet supported in Node v12. Without this it works now again. Fixed in the next version

**Closed by AnWeber** 2021-12-05 20:26 UTC
